### ISSUE TITLE
Add test to check light interception

### ISSUE THREAD

**Issue by pradal** [openalea-incubator/WALTer#31] opened 2018-03-05 13:18 UTC
We want to test Lstring values and Walter dict.

There are 2 issues that are blocking. Create tests that fails. Then fix the bug.

**Comment by christian34** [comment] 2018-03-22 09:03
I complete two test in PR #34 : 

- For zero light, I cannot reproduce the bug with my environment (=> to be further investigated)
- For day to day variation the test seems to reproduce the bug (still always less than 1000 %)

As the tests have been created, May be can we close this issue and continue discussion in the bloking issue / PR #34 ?

**Comment by christian34** [comment] 2018-03-27 13:30
done with #34 merge

**Closed by christian34** 2018-03-27 13:30 UTC
