### ISSUE TITLE
Important changes in intercepted PAR

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#14] opened 2017-12-05 10:21 UTC
The PAR intercepted by each plant is measured for each day in the model. For some plants there are **very** important changes in the intercepted PAR between one day and the next day

**Comment by christian34** [comment] 2017-12-07 17:12
Can you post the input parameters that produce that bug, together with the output to look at to see it ?

**Comment by pradal** [comment] 2017-12-07 17:44
The best solution would be to write another test that reproduce the problem:

**Comment by Emblanc** [comment] 2017-12-08 11:34
To my knowledge, this problem occurs in any simulation. When we look at the PAR_per_axes.csv file, we can see values such as 10^6 µmol of PAR/m^2 for some plants on a specific day

**Comment by pradal** [comment] 2018-03-05 13:10
The bug is in the scene management in Walter.
Caribu computes correctly the light (dixit @Emblanc ) but Walter change in some way this information.

**Comment by christian34** [comment] 2018-03-22 09:57
Okay the bug (and the strange PAR) value comes form bad light sources definition (negative energy light sources). This may be due to the use of old and probably deprecated GenSky tool. I will add a test on it.

My suggestion will however to switch to astk.sun_and_sky module and re-test if the bug is still there (I will add some lines in PR #34 )

**Comment by christian34** [comment] 2018-03-22 14:40
I fix the sky generation bug (wrong indexing of GenSky outputs) in PR #34 .
The test still has day to day variation of light, but in a range that seems similar to day to day variation of PAR. Further check would need to add Current_PAR in output file.
To me the bug is fixed: @Emblanc : is it okay for you ?

**Comment by christian34** [comment] 2018-03-27 14:35
I just figured out that scene unit are in cm, whilst scen_unit are set to m in caribu call: I will fix that in PR #17

**Comment by christian34** [comment] 2018-03-27 16:01
Hum, may be it is better to address this unit concern in a separate issue: I will open a new issue /PR on that topic

**Comment by pradal** [comment] 2018-04-03 17:26
@Emblanc @christian34 Can we close this issue?

**Comment by christian34** [comment] 2018-04-04 07:29
Yes for me it's okay !

**Comment by Emblanc** [comment] 2018-04-05 12:02
Yes, we can close this issue.

**Closed** 2018-04-05 12:24 UTC
Labels: Blocker, bug
